#!/bin/bash -eu

for PKG in "$@"; do
    INSTALLED=$(cargo install --list | sed -n 's/^'"${PKG}"' v\(.*\):$/\1/p')
    AVAILABLE=$(cargo search "${PKG}" | sed -n 's/^'"${PKG}"' = "\([^"]*\)".*$/\1/p')

    echo "${PKG}: installed=${INSTALLED:-N/A}, available=${AVAILABLE:-N/A}"
    if [[ "${AVAILABLE}" == "" ]]; then
        echo "Package \"${PKG}\" not found" >&2
        exit 1
    fi

    if [[ "${INSTALLED}" != "${AVAILABLE}" ]]; then
        cargo install "${PKG}" --force
    fi
done
